version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  target-branch: main
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  target-branch: main
